language: groovy
jdk:
- oraclejdk8
sudo: required
before_install:
- gem install sass
- npm install -g bower
- wget http://repo.spring.io/release/org/springframework/boot/spring-boot-cli/1.2.3.RELEASE/spring-boot-cli-1.2.3.RELEASE-bin.tar.gz
- tar xvfz spring-boot-cli-1.2.3.RELEASE-bin.tar.gz
- export PATH=$PATH:spring-1.2.3.RELEASE/bin
- spring --version
- wget -O cf-linux-amd64.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.11.2&source=github-rel"
- tar xvfz cf-linux-amd64.tgz
- chmod 755 ./cf
script:
- ./build
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" -a "${TRAVIS_BRANCH}" = "master" ]; then ./deploy ; fi
notifications:
  slack:
    secure: gmYkjOhLkUAlu2ml4daoSN+iu5dhrjEooeRwKtwNQHTSBLqjNQPw/iJ8yj+sGpaqqTiBtFy/PvbQ3OeOrgp88uCv3YrYCI1M5cHh7OlX/Z4MIdOMpRmJLf8wNnPLcKqzhpII4sjD9R/J/MlqfhpJFqqiikiP5nTVziSQV5VqWU4=
